@host=http://localhost:3000

### regist
POST {{host}}/api/regist
Content-Type: application/json

{
  "nickname": "rim11",
  "email": "leeyerim@naver.com",
  "passwd": "password123"
}

### regist
POST {{host}}/api/regist
Content-Type: application/json

{
  "email": "hiikim@gmail",
  "passwd": "password11"
}