import type { Metadata } from 'next';
import './globals.css';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className='font-serif'>
        <header className='text-xl px-4 py-2'>Rimi&apos;s Bookmark</header>
        <hr />
        <main>{children}</main>
        <hr />
        <footer className='mt-2 text-center'>©yrlee</footer>
      </body>
    </html>
  );
}
